default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: admin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pj-distrib

test:
  <<: *default
  database: pj-distrib_test
